/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_window_main_gp (void);
GtkWidget* create_window_ajout_gp (void);
GtkWidget* create_window_modification_gp (void);
GtkWidget* create_window_suppression_gp (void);
GtkWidget* create_window_notification_gp (void);
GtkWidget* create_window_p2_gp_detail (void);
GtkWidget* create_window_p2_gp_ajout (void);
GtkWidget* create_window_p2_notification_gp (void);
