/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "header_gp.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *window_main_gp;
  GtkWidget *treeview1_gp;
  GtkWidget *window_ajout_gp;
  GtkWidget *combobox1,*input1,*JOUR,*MOIS,*ANNEE;
  PangoFontDescription *fontDesc =pango_font_description_from_string( "monospace 20" );



#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  window_main_gp = create_window_main_gp ();
  gtk_widget_show(window_main_gp);
  treeview1_gp=lookup_widget(window_main_gp,"treeview1_gp");
  afficher_plante(treeview1_gp);
  combobox1=lookup_widget(window_main_gp,"combobox_filtre_nom_gp");
  gtk_combo_box_set_active(GTK_COMBO_BOX(combobox1),0);
  input1=lookup_widget(window_main_gp,"entry_id_gp");
  JOUR=lookup_widget(window_main_gp,"spinbutton_jour_gp");
  MOIS=lookup_widget(window_main_gp,"spinbutton_mois_gp");
  ANNEE=lookup_widget(window_main_gp,"spinbutton_annee_gp");
  gtk_widget_modify_font(input1,fontDesc);
  gtk_widget_modify_font(JOUR,fontDesc);
  gtk_widget_modify_font(MOIS,fontDesc);
  gtk_widget_modify_font(ANNEE,fontDesc);

  gtk_main ();
  return 0;
}

